# Generated by Django 4.2.5 on 2023-09-26 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('next_run', models.DateTimeField(auto_now=True, verbose_name='Дата следующей рассылки')),
                ('frequency', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=30, verbose_name='Периодичность')),
                ('status_sending', models.CharField(choices=[('Завершена', 'завершена'), ('Создана', 'создана'), ('Запущена', 'активирована')], max_length=30, verbose_name='Статус')),
                ('start_sending_date', models.DateField(default=datetime.datetime(2023, 9, 26, 18, 55, 3, 402558), verbose_name='Дата начала')),
                ('start_sending_time', models.TimeField(blank=True, default=datetime.time(18, 55, 3, 402567), null=True, verbose_name='время рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('can_view_sending', 'Can view sending'), ('can_disable_sending', 'Can disable sending')],
            },
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='message',
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='log',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='log',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AddField(
            model_name='log',
            name='answer_server',
            field=models.CharField(default='', max_length=20, verbose_name='Ответ почтового сервера'),
        ),
        migrations.AddField(
            model_name='log',
            name='status_attempt',
            field=models.CharField(choices=[('success', 'завершена'), ('failure', 'провалена'), ('in_progress', 'в процессе')], default='in_progress', max_length=30, verbose_name='Текущий статус'),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='', verbose_name='Контент'),
        ),
    ]
