# Generated by Django 4.2.5 on 2023-09-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_initial'),
        ('mailing', '0002_sending_remove_mailing_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='log',
            name='last_attempt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последней попытки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.AddField(
            model_name='sending',
            name='customer',
            field=models.ManyToManyField(to='customer.customer', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='sending',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='sending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='log',
            name='sending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.sending', verbose_name='Письмо'),
        ),
    ]
