# Generated by Django 4.2.5 on 2023-09-26 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_message_user_alter_log_last_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='start_sending_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 18, 57, 57, 80120), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 57, 57, 80135), null=True, verbose_name='время рассылки'),
        ),
    ]
